//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Input System/Main Interface Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Core.UI.Utility.Input
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input System/Main Interface Controls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @MainInterfaceControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @MainInterfaceControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Main Interface Controls"",
    ""maps"": [
        {
            ""name"": ""Information Display"",
            ""id"": ""ad8b20ae-f0b3-4832-8e7f-83a040025a83"",
            ""actions"": [
                {
                    ""name"": ""Display Skill Information"",
                    ""type"": ""Button"",
                    ""id"": ""58882f9f-3151-498c-918d-10e8df8a2788"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Display Character Stat Point Information"",
                    ""type"": ""Button"",
                    ""id"": ""5bb7c706-9425-4182-a815-552fbd18e73f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b8d658f-1ecb-4d22-8fe9-293e6e7da3b9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Display Skill Information"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e00dc5f7-5f30-4a13-8928-954256bccabd"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Display Character Stat Point Information"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pause Button"",
            ""id"": ""448e4283-80f2-4400-80a1-0a6fe6c5a75e"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""aca5d531-59a2-4150-8075-7231a6f5d3cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7eca0bdd-a779-4d91-abb7-96a0aba60979"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Quit Button"",
            ""id"": ""a65afd21-8549-47e4-b6b3-820e2a4d41b5"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""9005d84f-8771-497f-96cb-2bda50f58235"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b4a2dab-863d-401f-a2de-254b3d638bec"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Window Platform"",
            ""bindingGroup"": ""Window Platform"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Information Display
            m_InformationDisplay = asset.FindActionMap("Information Display", throwIfNotFound: true);
            m_InformationDisplay_DisplaySkillInformation = m_InformationDisplay.FindAction("Display Skill Information", throwIfNotFound: true);
            m_InformationDisplay_DisplayCharacterStatPointInformation = m_InformationDisplay.FindAction("Display Character Stat Point Information", throwIfNotFound: true);
            // Pause Button
            m_PauseButton = asset.FindActionMap("Pause Button", throwIfNotFound: true);
            m_PauseButton_Toggle = m_PauseButton.FindAction("Toggle", throwIfNotFound: true);
            // Quit Button
            m_QuitButton = asset.FindActionMap("Quit Button", throwIfNotFound: true);
            m_QuitButton_Toggle = m_QuitButton.FindAction("Toggle", throwIfNotFound: true);
        }

        ~@MainInterfaceControls()
        {
            UnityEngine.Debug.Assert(!m_InformationDisplay.enabled, "This will cause a leak and performance issues, MainInterfaceControls.InformationDisplay.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_PauseButton.enabled, "This will cause a leak and performance issues, MainInterfaceControls.PauseButton.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_QuitButton.enabled, "This will cause a leak and performance issues, MainInterfaceControls.QuitButton.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Information Display
        private readonly InputActionMap m_InformationDisplay;
        private List<IInformationDisplayActions> m_InformationDisplayActionsCallbackInterfaces = new List<IInformationDisplayActions>();
        private readonly InputAction m_InformationDisplay_DisplaySkillInformation;
        private readonly InputAction m_InformationDisplay_DisplayCharacterStatPointInformation;
        /// <summary>
        /// Provides access to input actions defined in input action map "Information Display".
        /// </summary>
        public struct InformationDisplayActions
        {
            private @MainInterfaceControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public InformationDisplayActions(@MainInterfaceControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "InformationDisplay/DisplaySkillInformation".
            /// </summary>
            public InputAction @DisplaySkillInformation => m_Wrapper.m_InformationDisplay_DisplaySkillInformation;
            /// <summary>
            /// Provides access to the underlying input action "InformationDisplay/DisplayCharacterStatPointInformation".
            /// </summary>
            public InputAction @DisplayCharacterStatPointInformation => m_Wrapper.m_InformationDisplay_DisplayCharacterStatPointInformation;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_InformationDisplay; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="InformationDisplayActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(InformationDisplayActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="InformationDisplayActions" />
            public void AddCallbacks(IInformationDisplayActions instance)
            {
                if (instance == null || m_Wrapper.m_InformationDisplayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_InformationDisplayActionsCallbackInterfaces.Add(instance);
                @DisplaySkillInformation.started += instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.performed += instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.canceled += instance.OnDisplaySkillInformation;
                @DisplayCharacterStatPointInformation.started += instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.performed += instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.canceled += instance.OnDisplayCharacterStatPointInformation;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="InformationDisplayActions" />
            private void UnregisterCallbacks(IInformationDisplayActions instance)
            {
                @DisplaySkillInformation.started -= instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.performed -= instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.canceled -= instance.OnDisplaySkillInformation;
                @DisplayCharacterStatPointInformation.started -= instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.performed -= instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.canceled -= instance.OnDisplayCharacterStatPointInformation;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InformationDisplayActions.UnregisterCallbacks(IInformationDisplayActions)" />.
            /// </summary>
            /// <seealso cref="InformationDisplayActions.UnregisterCallbacks(IInformationDisplayActions)" />
            public void RemoveCallbacks(IInformationDisplayActions instance)
            {
                if (m_Wrapper.m_InformationDisplayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="InformationDisplayActions.AddCallbacks(IInformationDisplayActions)" />
            /// <seealso cref="InformationDisplayActions.RemoveCallbacks(IInformationDisplayActions)" />
            /// <seealso cref="InformationDisplayActions.UnregisterCallbacks(IInformationDisplayActions)" />
            public void SetCallbacks(IInformationDisplayActions instance)
            {
                foreach (var item in m_Wrapper.m_InformationDisplayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_InformationDisplayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="InformationDisplayActions" /> instance referencing this action map.
        /// </summary>
        public InformationDisplayActions @InformationDisplay => new InformationDisplayActions(this);

        // Pause Button
        private readonly InputActionMap m_PauseButton;
        private List<IPauseButtonActions> m_PauseButtonActionsCallbackInterfaces = new List<IPauseButtonActions>();
        private readonly InputAction m_PauseButton_Toggle;
        /// <summary>
        /// Provides access to input actions defined in input action map "Pause Button".
        /// </summary>
        public struct PauseButtonActions
        {
            private @MainInterfaceControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public PauseButtonActions(@MainInterfaceControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "PauseButton/Toggle".
            /// </summary>
            public InputAction @Toggle => m_Wrapper.m_PauseButton_Toggle;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_PauseButton; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="PauseButtonActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(PauseButtonActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="PauseButtonActions" />
            public void AddCallbacks(IPauseButtonActions instance)
            {
                if (instance == null || m_Wrapper.m_PauseButtonActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PauseButtonActionsCallbackInterfaces.Add(instance);
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="PauseButtonActions" />
            private void UnregisterCallbacks(IPauseButtonActions instance)
            {
                @Toggle.started -= instance.OnToggle;
                @Toggle.performed -= instance.OnToggle;
                @Toggle.canceled -= instance.OnToggle;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PauseButtonActions.UnregisterCallbacks(IPauseButtonActions)" />.
            /// </summary>
            /// <seealso cref="PauseButtonActions.UnregisterCallbacks(IPauseButtonActions)" />
            public void RemoveCallbacks(IPauseButtonActions instance)
            {
                if (m_Wrapper.m_PauseButtonActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="PauseButtonActions.AddCallbacks(IPauseButtonActions)" />
            /// <seealso cref="PauseButtonActions.RemoveCallbacks(IPauseButtonActions)" />
            /// <seealso cref="PauseButtonActions.UnregisterCallbacks(IPauseButtonActions)" />
            public void SetCallbacks(IPauseButtonActions instance)
            {
                foreach (var item in m_Wrapper.m_PauseButtonActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PauseButtonActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="PauseButtonActions" /> instance referencing this action map.
        /// </summary>
        public PauseButtonActions @PauseButton => new PauseButtonActions(this);

        // Quit Button
        private readonly InputActionMap m_QuitButton;
        private List<IQuitButtonActions> m_QuitButtonActionsCallbackInterfaces = new List<IQuitButtonActions>();
        private readonly InputAction m_QuitButton_Toggle;
        /// <summary>
        /// Provides access to input actions defined in input action map "Quit Button".
        /// </summary>
        public struct QuitButtonActions
        {
            private @MainInterfaceControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public QuitButtonActions(@MainInterfaceControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "QuitButton/Toggle".
            /// </summary>
            public InputAction @Toggle => m_Wrapper.m_QuitButton_Toggle;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_QuitButton; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="QuitButtonActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(QuitButtonActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="QuitButtonActions" />
            public void AddCallbacks(IQuitButtonActions instance)
            {
                if (instance == null || m_Wrapper.m_QuitButtonActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_QuitButtonActionsCallbackInterfaces.Add(instance);
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="QuitButtonActions" />
            private void UnregisterCallbacks(IQuitButtonActions instance)
            {
                @Toggle.started -= instance.OnToggle;
                @Toggle.performed -= instance.OnToggle;
                @Toggle.canceled -= instance.OnToggle;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="QuitButtonActions.UnregisterCallbacks(IQuitButtonActions)" />.
            /// </summary>
            /// <seealso cref="QuitButtonActions.UnregisterCallbacks(IQuitButtonActions)" />
            public void RemoveCallbacks(IQuitButtonActions instance)
            {
                if (m_Wrapper.m_QuitButtonActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="QuitButtonActions.AddCallbacks(IQuitButtonActions)" />
            /// <seealso cref="QuitButtonActions.RemoveCallbacks(IQuitButtonActions)" />
            /// <seealso cref="QuitButtonActions.UnregisterCallbacks(IQuitButtonActions)" />
            public void SetCallbacks(IQuitButtonActions instance)
            {
                foreach (var item in m_Wrapper.m_QuitButtonActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_QuitButtonActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="QuitButtonActions" /> instance referencing this action map.
        /// </summary>
        public QuitButtonActions @QuitButton => new QuitButtonActions(this);
        private int m_WindowPlatformSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme WindowPlatformScheme
        {
            get
            {
                if (m_WindowPlatformSchemeIndex == -1) m_WindowPlatformSchemeIndex = asset.FindControlSchemeIndex("Window Platform");
                return asset.controlSchemes[m_WindowPlatformSchemeIndex];
            }
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Information Display" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="InformationDisplayActions.AddCallbacks(IInformationDisplayActions)" />
        /// <seealso cref="InformationDisplayActions.RemoveCallbacks(IInformationDisplayActions)" />
        public interface IInformationDisplayActions
        {
            /// <summary>
            /// Method invoked when associated input action "Display Skill Information" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDisplaySkillInformation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Display Character Stat Point Information" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDisplayCharacterStatPointInformation(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Pause Button" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="PauseButtonActions.AddCallbacks(IPauseButtonActions)" />
        /// <seealso cref="PauseButtonActions.RemoveCallbacks(IPauseButtonActions)" />
        public interface IPauseButtonActions
        {
            /// <summary>
            /// Method invoked when associated input action "Toggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggle(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Quit Button" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="QuitButtonActions.AddCallbacks(IQuitButtonActions)" />
        /// <seealso cref="QuitButtonActions.RemoveCallbacks(IQuitButtonActions)" />
        public interface IQuitButtonActions
        {
            /// <summary>
            /// Method invoked when associated input action "Toggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggle(InputAction.CallbackContext context);
        }
    }
}
