//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Input System/UI Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Core.UI.Utility.Input
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input System/UI Controls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @UIControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @UIControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""UI Controls"",
    ""maps"": [
        {
            ""name"": ""Introduction Video"",
            ""id"": ""b26a79fe-d147-4a37-a991-a5dbd4afe259"",
            ""actions"": [
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""04c293b8-57fa-463a-9a1c-0c0421317035"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1628c6c9-32bb-4cc9-8606-375c60281fc8"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Title"",
            ""id"": ""044db425-45e5-4197-a394-a1c86b705731"",
            ""actions"": [
                {
                    ""name"": ""To Chapter Selection"",
                    ""type"": ""Button"",
                    ""id"": ""6771a31a-c0c9-42a8-b41e-5b6cfdc4dafa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba98d5d8-30e1-4265-95bd-882d73f7883e"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""To Chapter Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Chapter Selection"",
            ""id"": ""fd5e3fa7-0181-431c-b0de-68b70ed3346e"",
            ""actions"": [
                {
                    ""name"": ""Select Next Chapter"",
                    ""type"": ""Button"",
                    ""id"": ""4603a1f8-cdcd-45e2-be04-d5f8f55d2e56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Previous Chapter"",
                    ""type"": ""Button"",
                    ""id"": ""6c997041-541e-439a-8feb-17119e34f98d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return To Title"",
                    ""type"": ""Button"",
                    ""id"": ""4db22f72-b5da-4957-9faa-d3e4e0d63fee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""836bd202-75bb-47c4-b845-6cd77e32eb25"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Return To Title"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a2515e6-8423-4e84-9956-1a2a0683b1bb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Select Next Chapter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55ae40a5-3e1e-4551-a3ce-796cace1f6bc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Select Previous Chapter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Main Interface"",
            ""id"": ""e24469ad-fcda-4a81-8644-88114c7b7553"",
            ""actions"": [
                {
                    ""name"": ""Display Skill Information"",
                    ""type"": ""Button"",
                    ""id"": ""1f6a33fb-0533-4e15-9ca3-ec62e52fec16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Display Character Stat Point Information"",
                    ""type"": ""Button"",
                    ""id"": ""a0501f39-7329-4190-b94f-334097d93f08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""d5bebd59-f577-49fe-beb9-cef218858417"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""fc39d9f2-f615-45e1-8ab8-a0fc2ebe52a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""65e04fb2-9523-4fab-b84c-a14da9081a31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4bb956b5-4ca4-4e07-96b9-94aa4336dc0a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Display Skill Information"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfd39c29-7f11-4aa6-801e-e9e757923d81"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Display Character Stat Point Information"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""112698e9-06ca-472f-b3f2-6619ce17374f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3bf7a3d-89fb-4fe9-80dc-df1e1c8fac2b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f93deea-652a-4a8e-ab6b-2ddba09cf27d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Victory Result"",
            ""id"": ""912ec474-4893-4a6b-b1d4-aed7165e6860"",
            ""actions"": [
                {
                    ""name"": ""Return To Title"",
                    ""type"": ""Button"",
                    ""id"": ""0c8c7593-0fc3-4217-b0d6-4140bf275fc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4449c7d-7831-4c1d-801a-ddee2e242de7"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Return To Title"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Failed Result"",
            ""id"": ""1b62eadc-5fdc-42f8-aa86-4aa2bf5569c2"",
            ""actions"": [
                {
                    ""name"": ""Open Dialog Screen"",
                    ""type"": ""Button"",
                    ""id"": ""982d8211-9a54-47fa-b9fc-5bbbdb18faab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c5f9076c-2d00-4c18-b9a6-454df535c1a1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Window Platform"",
                    ""action"": ""Open Dialog Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Window Platform"",
            ""bindingGroup"": ""Window Platform"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Introduction Video
            m_IntroductionVideo = asset.FindActionMap("Introduction Video", throwIfNotFound: true);
            m_IntroductionVideo_Skip = m_IntroductionVideo.FindAction("Skip", throwIfNotFound: true);
            // Title
            m_Title = asset.FindActionMap("Title", throwIfNotFound: true);
            m_Title_ToChapterSelection = m_Title.FindAction("To Chapter Selection", throwIfNotFound: true);
            // Chapter Selection
            m_ChapterSelection = asset.FindActionMap("Chapter Selection", throwIfNotFound: true);
            m_ChapterSelection_SelectNextChapter = m_ChapterSelection.FindAction("Select Next Chapter", throwIfNotFound: true);
            m_ChapterSelection_SelectPreviousChapter = m_ChapterSelection.FindAction("Select Previous Chapter", throwIfNotFound: true);
            m_ChapterSelection_ReturnToTitle = m_ChapterSelection.FindAction("Return To Title", throwIfNotFound: true);
            // Main Interface
            m_MainInterface = asset.FindActionMap("Main Interface", throwIfNotFound: true);
            m_MainInterface_DisplaySkillInformation = m_MainInterface.FindAction("Display Skill Information", throwIfNotFound: true);
            m_MainInterface_DisplayCharacterStatPointInformation = m_MainInterface.FindAction("Display Character Stat Point Information", throwIfNotFound: true);
            m_MainInterface_Restart = m_MainInterface.FindAction("Restart", throwIfNotFound: true);
            m_MainInterface_Pause = m_MainInterface.FindAction("Pause", throwIfNotFound: true);
            m_MainInterface_Quit = m_MainInterface.FindAction("Quit", throwIfNotFound: true);
            // Victory Result
            m_VictoryResult = asset.FindActionMap("Victory Result", throwIfNotFound: true);
            m_VictoryResult_ReturnToTitle = m_VictoryResult.FindAction("Return To Title", throwIfNotFound: true);
            // Failed Result
            m_FailedResult = asset.FindActionMap("Failed Result", throwIfNotFound: true);
            m_FailedResult_OpenDialogScreen = m_FailedResult.FindAction("Open Dialog Screen", throwIfNotFound: true);
        }

        ~@UIControls()
        {
            UnityEngine.Debug.Assert(!m_IntroductionVideo.enabled, "This will cause a leak and performance issues, UIControls.IntroductionVideo.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Title.enabled, "This will cause a leak and performance issues, UIControls.Title.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_ChapterSelection.enabled, "This will cause a leak and performance issues, UIControls.ChapterSelection.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_MainInterface.enabled, "This will cause a leak and performance issues, UIControls.MainInterface.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_VictoryResult.enabled, "This will cause a leak and performance issues, UIControls.VictoryResult.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_FailedResult.enabled, "This will cause a leak and performance issues, UIControls.FailedResult.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Introduction Video
        private readonly InputActionMap m_IntroductionVideo;
        private List<IIntroductionVideoActions> m_IntroductionVideoActionsCallbackInterfaces = new List<IIntroductionVideoActions>();
        private readonly InputAction m_IntroductionVideo_Skip;
        /// <summary>
        /// Provides access to input actions defined in input action map "Introduction Video".
        /// </summary>
        public struct IntroductionVideoActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public IntroductionVideoActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "IntroductionVideo/Skip".
            /// </summary>
            public InputAction @Skip => m_Wrapper.m_IntroductionVideo_Skip;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_IntroductionVideo; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="IntroductionVideoActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(IntroductionVideoActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="IntroductionVideoActions" />
            public void AddCallbacks(IIntroductionVideoActions instance)
            {
                if (instance == null || m_Wrapper.m_IntroductionVideoActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_IntroductionVideoActionsCallbackInterfaces.Add(instance);
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="IntroductionVideoActions" />
            private void UnregisterCallbacks(IIntroductionVideoActions instance)
            {
                @Skip.started -= instance.OnSkip;
                @Skip.performed -= instance.OnSkip;
                @Skip.canceled -= instance.OnSkip;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="IntroductionVideoActions.UnregisterCallbacks(IIntroductionVideoActions)" />.
            /// </summary>
            /// <seealso cref="IntroductionVideoActions.UnregisterCallbacks(IIntroductionVideoActions)" />
            public void RemoveCallbacks(IIntroductionVideoActions instance)
            {
                if (m_Wrapper.m_IntroductionVideoActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="IntroductionVideoActions.AddCallbacks(IIntroductionVideoActions)" />
            /// <seealso cref="IntroductionVideoActions.RemoveCallbacks(IIntroductionVideoActions)" />
            /// <seealso cref="IntroductionVideoActions.UnregisterCallbacks(IIntroductionVideoActions)" />
            public void SetCallbacks(IIntroductionVideoActions instance)
            {
                foreach (var item in m_Wrapper.m_IntroductionVideoActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_IntroductionVideoActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="IntroductionVideoActions" /> instance referencing this action map.
        /// </summary>
        public IntroductionVideoActions @IntroductionVideo => new IntroductionVideoActions(this);

        // Title
        private readonly InputActionMap m_Title;
        private List<ITitleActions> m_TitleActionsCallbackInterfaces = new List<ITitleActions>();
        private readonly InputAction m_Title_ToChapterSelection;
        /// <summary>
        /// Provides access to input actions defined in input action map "Title".
        /// </summary>
        public struct TitleActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public TitleActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Title/ToChapterSelection".
            /// </summary>
            public InputAction @ToChapterSelection => m_Wrapper.m_Title_ToChapterSelection;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Title; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="TitleActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(TitleActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="TitleActions" />
            public void AddCallbacks(ITitleActions instance)
            {
                if (instance == null || m_Wrapper.m_TitleActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_TitleActionsCallbackInterfaces.Add(instance);
                @ToChapterSelection.started += instance.OnToChapterSelection;
                @ToChapterSelection.performed += instance.OnToChapterSelection;
                @ToChapterSelection.canceled += instance.OnToChapterSelection;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="TitleActions" />
            private void UnregisterCallbacks(ITitleActions instance)
            {
                @ToChapterSelection.started -= instance.OnToChapterSelection;
                @ToChapterSelection.performed -= instance.OnToChapterSelection;
                @ToChapterSelection.canceled -= instance.OnToChapterSelection;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TitleActions.UnregisterCallbacks(ITitleActions)" />.
            /// </summary>
            /// <seealso cref="TitleActions.UnregisterCallbacks(ITitleActions)" />
            public void RemoveCallbacks(ITitleActions instance)
            {
                if (m_Wrapper.m_TitleActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="TitleActions.AddCallbacks(ITitleActions)" />
            /// <seealso cref="TitleActions.RemoveCallbacks(ITitleActions)" />
            /// <seealso cref="TitleActions.UnregisterCallbacks(ITitleActions)" />
            public void SetCallbacks(ITitleActions instance)
            {
                foreach (var item in m_Wrapper.m_TitleActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_TitleActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="TitleActions" /> instance referencing this action map.
        /// </summary>
        public TitleActions @Title => new TitleActions(this);

        // Chapter Selection
        private readonly InputActionMap m_ChapterSelection;
        private List<IChapterSelectionActions> m_ChapterSelectionActionsCallbackInterfaces = new List<IChapterSelectionActions>();
        private readonly InputAction m_ChapterSelection_SelectNextChapter;
        private readonly InputAction m_ChapterSelection_SelectPreviousChapter;
        private readonly InputAction m_ChapterSelection_ReturnToTitle;
        /// <summary>
        /// Provides access to input actions defined in input action map "Chapter Selection".
        /// </summary>
        public struct ChapterSelectionActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ChapterSelectionActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "ChapterSelection/SelectNextChapter".
            /// </summary>
            public InputAction @SelectNextChapter => m_Wrapper.m_ChapterSelection_SelectNextChapter;
            /// <summary>
            /// Provides access to the underlying input action "ChapterSelection/SelectPreviousChapter".
            /// </summary>
            public InputAction @SelectPreviousChapter => m_Wrapper.m_ChapterSelection_SelectPreviousChapter;
            /// <summary>
            /// Provides access to the underlying input action "ChapterSelection/ReturnToTitle".
            /// </summary>
            public InputAction @ReturnToTitle => m_Wrapper.m_ChapterSelection_ReturnToTitle;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_ChapterSelection; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ChapterSelectionActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ChapterSelectionActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ChapterSelectionActions" />
            public void AddCallbacks(IChapterSelectionActions instance)
            {
                if (instance == null || m_Wrapper.m_ChapterSelectionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ChapterSelectionActionsCallbackInterfaces.Add(instance);
                @SelectNextChapter.started += instance.OnSelectNextChapter;
                @SelectNextChapter.performed += instance.OnSelectNextChapter;
                @SelectNextChapter.canceled += instance.OnSelectNextChapter;
                @SelectPreviousChapter.started += instance.OnSelectPreviousChapter;
                @SelectPreviousChapter.performed += instance.OnSelectPreviousChapter;
                @SelectPreviousChapter.canceled += instance.OnSelectPreviousChapter;
                @ReturnToTitle.started += instance.OnReturnToTitle;
                @ReturnToTitle.performed += instance.OnReturnToTitle;
                @ReturnToTitle.canceled += instance.OnReturnToTitle;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ChapterSelectionActions" />
            private void UnregisterCallbacks(IChapterSelectionActions instance)
            {
                @SelectNextChapter.started -= instance.OnSelectNextChapter;
                @SelectNextChapter.performed -= instance.OnSelectNextChapter;
                @SelectNextChapter.canceled -= instance.OnSelectNextChapter;
                @SelectPreviousChapter.started -= instance.OnSelectPreviousChapter;
                @SelectPreviousChapter.performed -= instance.OnSelectPreviousChapter;
                @SelectPreviousChapter.canceled -= instance.OnSelectPreviousChapter;
                @ReturnToTitle.started -= instance.OnReturnToTitle;
                @ReturnToTitle.performed -= instance.OnReturnToTitle;
                @ReturnToTitle.canceled -= instance.OnReturnToTitle;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ChapterSelectionActions.UnregisterCallbacks(IChapterSelectionActions)" />.
            /// </summary>
            /// <seealso cref="ChapterSelectionActions.UnregisterCallbacks(IChapterSelectionActions)" />
            public void RemoveCallbacks(IChapterSelectionActions instance)
            {
                if (m_Wrapper.m_ChapterSelectionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ChapterSelectionActions.AddCallbacks(IChapterSelectionActions)" />
            /// <seealso cref="ChapterSelectionActions.RemoveCallbacks(IChapterSelectionActions)" />
            /// <seealso cref="ChapterSelectionActions.UnregisterCallbacks(IChapterSelectionActions)" />
            public void SetCallbacks(IChapterSelectionActions instance)
            {
                foreach (var item in m_Wrapper.m_ChapterSelectionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ChapterSelectionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ChapterSelectionActions" /> instance referencing this action map.
        /// </summary>
        public ChapterSelectionActions @ChapterSelection => new ChapterSelectionActions(this);

        // Main Interface
        private readonly InputActionMap m_MainInterface;
        private List<IMainInterfaceActions> m_MainInterfaceActionsCallbackInterfaces = new List<IMainInterfaceActions>();
        private readonly InputAction m_MainInterface_DisplaySkillInformation;
        private readonly InputAction m_MainInterface_DisplayCharacterStatPointInformation;
        private readonly InputAction m_MainInterface_Restart;
        private readonly InputAction m_MainInterface_Pause;
        private readonly InputAction m_MainInterface_Quit;
        /// <summary>
        /// Provides access to input actions defined in input action map "Main Interface".
        /// </summary>
        public struct MainInterfaceActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MainInterfaceActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "MainInterface/DisplaySkillInformation".
            /// </summary>
            public InputAction @DisplaySkillInformation => m_Wrapper.m_MainInterface_DisplaySkillInformation;
            /// <summary>
            /// Provides access to the underlying input action "MainInterface/DisplayCharacterStatPointInformation".
            /// </summary>
            public InputAction @DisplayCharacterStatPointInformation => m_Wrapper.m_MainInterface_DisplayCharacterStatPointInformation;
            /// <summary>
            /// Provides access to the underlying input action "MainInterface/Restart".
            /// </summary>
            public InputAction @Restart => m_Wrapper.m_MainInterface_Restart;
            /// <summary>
            /// Provides access to the underlying input action "MainInterface/Pause".
            /// </summary>
            public InputAction @Pause => m_Wrapper.m_MainInterface_Pause;
            /// <summary>
            /// Provides access to the underlying input action "MainInterface/Quit".
            /// </summary>
            public InputAction @Quit => m_Wrapper.m_MainInterface_Quit;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_MainInterface; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MainInterfaceActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MainInterfaceActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MainInterfaceActions" />
            public void AddCallbacks(IMainInterfaceActions instance)
            {
                if (instance == null || m_Wrapper.m_MainInterfaceActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MainInterfaceActionsCallbackInterfaces.Add(instance);
                @DisplaySkillInformation.started += instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.performed += instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.canceled += instance.OnDisplaySkillInformation;
                @DisplayCharacterStatPointInformation.started += instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.performed += instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.canceled += instance.OnDisplayCharacterStatPointInformation;
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MainInterfaceActions" />
            private void UnregisterCallbacks(IMainInterfaceActions instance)
            {
                @DisplaySkillInformation.started -= instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.performed -= instance.OnDisplaySkillInformation;
                @DisplaySkillInformation.canceled -= instance.OnDisplaySkillInformation;
                @DisplayCharacterStatPointInformation.started -= instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.performed -= instance.OnDisplayCharacterStatPointInformation;
                @DisplayCharacterStatPointInformation.canceled -= instance.OnDisplayCharacterStatPointInformation;
                @Restart.started -= instance.OnRestart;
                @Restart.performed -= instance.OnRestart;
                @Restart.canceled -= instance.OnRestart;
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
                @Quit.started -= instance.OnQuit;
                @Quit.performed -= instance.OnQuit;
                @Quit.canceled -= instance.OnQuit;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MainInterfaceActions.UnregisterCallbacks(IMainInterfaceActions)" />.
            /// </summary>
            /// <seealso cref="MainInterfaceActions.UnregisterCallbacks(IMainInterfaceActions)" />
            public void RemoveCallbacks(IMainInterfaceActions instance)
            {
                if (m_Wrapper.m_MainInterfaceActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MainInterfaceActions.AddCallbacks(IMainInterfaceActions)" />
            /// <seealso cref="MainInterfaceActions.RemoveCallbacks(IMainInterfaceActions)" />
            /// <seealso cref="MainInterfaceActions.UnregisterCallbacks(IMainInterfaceActions)" />
            public void SetCallbacks(IMainInterfaceActions instance)
            {
                foreach (var item in m_Wrapper.m_MainInterfaceActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MainInterfaceActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MainInterfaceActions" /> instance referencing this action map.
        /// </summary>
        public MainInterfaceActions @MainInterface => new MainInterfaceActions(this);

        // Victory Result
        private readonly InputActionMap m_VictoryResult;
        private List<IVictoryResultActions> m_VictoryResultActionsCallbackInterfaces = new List<IVictoryResultActions>();
        private readonly InputAction m_VictoryResult_ReturnToTitle;
        /// <summary>
        /// Provides access to input actions defined in input action map "Victory Result".
        /// </summary>
        public struct VictoryResultActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public VictoryResultActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "VictoryResult/ReturnToTitle".
            /// </summary>
            public InputAction @ReturnToTitle => m_Wrapper.m_VictoryResult_ReturnToTitle;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_VictoryResult; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="VictoryResultActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(VictoryResultActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="VictoryResultActions" />
            public void AddCallbacks(IVictoryResultActions instance)
            {
                if (instance == null || m_Wrapper.m_VictoryResultActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_VictoryResultActionsCallbackInterfaces.Add(instance);
                @ReturnToTitle.started += instance.OnReturnToTitle;
                @ReturnToTitle.performed += instance.OnReturnToTitle;
                @ReturnToTitle.canceled += instance.OnReturnToTitle;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="VictoryResultActions" />
            private void UnregisterCallbacks(IVictoryResultActions instance)
            {
                @ReturnToTitle.started -= instance.OnReturnToTitle;
                @ReturnToTitle.performed -= instance.OnReturnToTitle;
                @ReturnToTitle.canceled -= instance.OnReturnToTitle;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="VictoryResultActions.UnregisterCallbacks(IVictoryResultActions)" />.
            /// </summary>
            /// <seealso cref="VictoryResultActions.UnregisterCallbacks(IVictoryResultActions)" />
            public void RemoveCallbacks(IVictoryResultActions instance)
            {
                if (m_Wrapper.m_VictoryResultActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="VictoryResultActions.AddCallbacks(IVictoryResultActions)" />
            /// <seealso cref="VictoryResultActions.RemoveCallbacks(IVictoryResultActions)" />
            /// <seealso cref="VictoryResultActions.UnregisterCallbacks(IVictoryResultActions)" />
            public void SetCallbacks(IVictoryResultActions instance)
            {
                foreach (var item in m_Wrapper.m_VictoryResultActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_VictoryResultActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="VictoryResultActions" /> instance referencing this action map.
        /// </summary>
        public VictoryResultActions @VictoryResult => new VictoryResultActions(this);

        // Failed Result
        private readonly InputActionMap m_FailedResult;
        private List<IFailedResultActions> m_FailedResultActionsCallbackInterfaces = new List<IFailedResultActions>();
        private readonly InputAction m_FailedResult_OpenDialogScreen;
        /// <summary>
        /// Provides access to input actions defined in input action map "Failed Result".
        /// </summary>
        public struct FailedResultActions
        {
            private @UIControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public FailedResultActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "FailedResult/OpenDialogScreen".
            /// </summary>
            public InputAction @OpenDialogScreen => m_Wrapper.m_FailedResult_OpenDialogScreen;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_FailedResult; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="FailedResultActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(FailedResultActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="FailedResultActions" />
            public void AddCallbacks(IFailedResultActions instance)
            {
                if (instance == null || m_Wrapper.m_FailedResultActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_FailedResultActionsCallbackInterfaces.Add(instance);
                @OpenDialogScreen.started += instance.OnOpenDialogScreen;
                @OpenDialogScreen.performed += instance.OnOpenDialogScreen;
                @OpenDialogScreen.canceled += instance.OnOpenDialogScreen;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="FailedResultActions" />
            private void UnregisterCallbacks(IFailedResultActions instance)
            {
                @OpenDialogScreen.started -= instance.OnOpenDialogScreen;
                @OpenDialogScreen.performed -= instance.OnOpenDialogScreen;
                @OpenDialogScreen.canceled -= instance.OnOpenDialogScreen;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FailedResultActions.UnregisterCallbacks(IFailedResultActions)" />.
            /// </summary>
            /// <seealso cref="FailedResultActions.UnregisterCallbacks(IFailedResultActions)" />
            public void RemoveCallbacks(IFailedResultActions instance)
            {
                if (m_Wrapper.m_FailedResultActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="FailedResultActions.AddCallbacks(IFailedResultActions)" />
            /// <seealso cref="FailedResultActions.RemoveCallbacks(IFailedResultActions)" />
            /// <seealso cref="FailedResultActions.UnregisterCallbacks(IFailedResultActions)" />
            public void SetCallbacks(IFailedResultActions instance)
            {
                foreach (var item in m_Wrapper.m_FailedResultActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_FailedResultActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="FailedResultActions" /> instance referencing this action map.
        /// </summary>
        public FailedResultActions @FailedResult => new FailedResultActions(this);
        private int m_WindowPlatformSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme WindowPlatformScheme
        {
            get
            {
                if (m_WindowPlatformSchemeIndex == -1) m_WindowPlatformSchemeIndex = asset.FindControlSchemeIndex("Window Platform");
                return asset.controlSchemes[m_WindowPlatformSchemeIndex];
            }
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Introduction Video" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="IntroductionVideoActions.AddCallbacks(IIntroductionVideoActions)" />
        /// <seealso cref="IntroductionVideoActions.RemoveCallbacks(IIntroductionVideoActions)" />
        public interface IIntroductionVideoActions
        {
            /// <summary>
            /// Method invoked when associated input action "Skip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSkip(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Title" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="TitleActions.AddCallbacks(ITitleActions)" />
        /// <seealso cref="TitleActions.RemoveCallbacks(ITitleActions)" />
        public interface ITitleActions
        {
            /// <summary>
            /// Method invoked when associated input action "To Chapter Selection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToChapterSelection(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Chapter Selection" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ChapterSelectionActions.AddCallbacks(IChapterSelectionActions)" />
        /// <seealso cref="ChapterSelectionActions.RemoveCallbacks(IChapterSelectionActions)" />
        public interface IChapterSelectionActions
        {
            /// <summary>
            /// Method invoked when associated input action "Select Next Chapter" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSelectNextChapter(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Select Previous Chapter" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSelectPreviousChapter(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Return To Title" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnReturnToTitle(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Main Interface" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MainInterfaceActions.AddCallbacks(IMainInterfaceActions)" />
        /// <seealso cref="MainInterfaceActions.RemoveCallbacks(IMainInterfaceActions)" />
        public interface IMainInterfaceActions
        {
            /// <summary>
            /// Method invoked when associated input action "Display Skill Information" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDisplaySkillInformation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Display Character Stat Point Information" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDisplayCharacterStatPointInformation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Restart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRestart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPause(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Quit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnQuit(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Victory Result" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="VictoryResultActions.AddCallbacks(IVictoryResultActions)" />
        /// <seealso cref="VictoryResultActions.RemoveCallbacks(IVictoryResultActions)" />
        public interface IVictoryResultActions
        {
            /// <summary>
            /// Method invoked when associated input action "Return To Title" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnReturnToTitle(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Failed Result" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="FailedResultActions.AddCallbacks(IFailedResultActions)" />
        /// <seealso cref="FailedResultActions.RemoveCallbacks(IFailedResultActions)" />
        public interface IFailedResultActions
        {
            /// <summary>
            /// Method invoked when associated input action "Open Dialog Screen" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOpenDialogScreen(InputAction.CallbackContext context);
        }
    }
}
